services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: .
        target: /app/
volumes:
  myapp:
